include:
- ./functions/library/Utils.py
- ./functions/model_training/__init__.py
- ./functions/model_training/model_training.py
- ./functions/model_training/build.sh
- ./functions/model_training/requirements.txt
kind: ArchiveUploadSpec
name: functions-library-utils-py-SwFc

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: model-training
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python-39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-library-utils-py-SwFc
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-14T11:41:29Z"
