include:
- ./functions/library/Utils.py
- ./functions/harvestweather/__init__.py
- ./functions/harvestweather/harvestweather.py
- ./functions/harvestweather/build.sh
- ./functions/harvestweather/requirements.txt
kind: ArchiveUploadSpec
name: functions-library-utils-py-WNoe

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: harvestweather
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python-39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-library-utils-py-WNoe
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-07T14:03:44Z"
