include:
- ./functions/library/Utils.py
- ./functions/get_analysis/__init__.py
- ./functions/get_analysis/get_analysis.py
- ./functions/get_analysis/build.sh
- ./functions/get_analysis/requirements.txt
kind: ArchiveUploadSpec
name: functions-library-utils-py-JjSR

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-analysis
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python-39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-library-utils-py-JjSR
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-15T11:35:11Z"
