apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: area-analysis-get
spec:
  createingress: false
  functionref:
    functionweights: null
    name: area-analysis
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /get_area/{area}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /get_area/{area}
