apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: query-analysis-get
spec:
  createingress: false
  functionref:
    functionweights: null
    name: query-analysis
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /analysis/{area}/{illness}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /analysis/{area}/{illness}
