apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-importances
spec:
  createingress: false
  functionref:
    functionweights: null
    name: get-importances
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /get_importances/{illness}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /get_importances/{illness}
