apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: affected-percentage-get
spec:
  createingress: false
  functionref:
    functionweights: null
    name: affected-percentage
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /affected_percentage/{illness}/{percentage}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /affected_percentage/{illness}/{percentage}
