apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: least-healthy-get
spec:
  createingress: false
  functionref:
    functionweights: null
    name: least-healthy
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /least_healthy
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /least_healthy
