apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: train-model
spec:
  createingress: false
  functionref:
    functionweights: null
    name: model-training
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /train_model
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /train_model
